"""create_marketplace_tables

Revision ID: 08980d11842a
Revises: cae58d178a60
Create Date: 2026-10-09 22:20:35.368060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08980d11842a'
down_revision: Union[str, Sequence[str], None] = 'cae58d178a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('size_acres', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('irrigation_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_owner_id'), ['owner_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('TRACTOR', 'HARVESTER', 'CULTIVATOR', 'SEED_DRILL', 'SPRAYER', 'DRONE', 'IRRIGATION_PUMP', 'TRANSPORT', 'LABOUR', 'HARVESTING_SERVICE', 'SPRAYING_SERVICE', 'OTHER', name='resourcecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('supported_operations', sa.JSON(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('pricing_unit', sa.Enum('PER_HOUR', 'PER_ACRE', 'PER_DAY', name='pricingunit'), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('service_radius_km', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_owner_id'), ['owner_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('planted_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crops_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crops_id'), ['id'], unique=False)

    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_windows_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_windows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_windows_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_windows_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_start_time'))
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_resource_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_end_time'))

    op.drop_table('maintenance_windows')
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crops_id'))
        batch_op.drop_index(batch_op.f('ix_crops_farm_id'))

    op.drop_table('crops')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_start_time'))
        batch_op.drop_index(batch_op.f('ix_bookings_resource_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_farm_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_end_time'))

    op.drop_table('bookings')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_owner_id'))
        batch_op.drop_index(batch_op.f('ix_resources_name'))
        batch_op.drop_index(batch_op.f('ix_resources_id'))
        batch_op.drop_index(batch_op.f('ix_resources_category'))

    op.drop_table('resources')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_farms_id'))

    op.drop_table('farms')
    # ### end Alembic commands ###
